apiVersion: v2
name: cinemagoapplication
description: A Helm chart to deploy Cinema project in Kubernetes
# chart type
type: application
# chart version
version: 0.2.0
# cinema app version
appVersion: "v2.1.0"
dependencies:
  - condition: mongodb.enabled
name: cinemagoapplication
    repository: https://charts.bitnami.com/bitnami
    version: 10.4.0
name: cinemagoapplication
    version: 0.x.x
name: cinemagoapplication
    version: 0.x.x
name: cinemagoapplication
    version: 0.x.x
name: cinemagoapplication
    version: 0.x.x
name: cinemagoapplication
    version: 0.x.x